language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .

# Command to run tests, e.g. python setup.py test
script:
  - coverage run test_epoch_analyzer.py

# Report to coveralls
after_success:
  - coveralls
